// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RetSiteCountMapSiteCounts = "site_counts"
	RetSiteCountProgCountSite = "count_site"
)

// LoadRetSiteCount returns the embedded CollectionSpec for RetSiteCount.
func LoadRetSiteCount() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RetSiteCountBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RetSiteCount: %w", err)
	}

	return spec, err
}

// LoadRetSiteCountObjects loads RetSiteCount and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RetSiteCountObjects
//	*RetSiteCountPrograms
//	*RetSiteCountMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRetSiteCountObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRetSiteCount()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RetSiteCountSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RetSiteCountSpecs struct {
	RetSiteCountProgramSpecs
	RetSiteCountMapSpecs
	RetSiteCountVariableSpecs
}

// RetSiteCountProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RetSiteCountProgramSpecs struct {
	CountSite *ebpf.ProgramSpec `ebpf:"count_site"`
}

// RetSiteCountMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RetSiteCountMapSpecs struct {
	SiteCounts *ebpf.MapSpec `ebpf:"site_counts"`
}

// RetSiteCountVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RetSiteCountVariableSpecs struct {
}

// RetSiteCountObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRetSiteCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type RetSiteCountObjects struct {
	RetSiteCountPrograms
	RetSiteCountMaps
	RetSiteCountVariables
}

func (o *RetSiteCountObjects) Close() error {
	return _RetSiteCountClose(
		&o.RetSiteCountPrograms,
		&o.RetSiteCountMaps,
	)
}

// RetSiteCountMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRetSiteCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type RetSiteCountMaps struct {
	SiteCounts *ebpf.Map `ebpf:"site_counts"`
}

func (m *RetSiteCountMaps) Close() error {
	return _RetSiteCountClose(
		m.SiteCounts,
	)
}

// RetSiteCountVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRetSiteCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type RetSiteCountVariables struct {
}

// RetSiteCountPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRetSiteCountObjects or ebpf.CollectionSpec.LoadAndAssign.
type RetSiteCountPrograms struct {
	CountSite *ebpf.Program `ebpf:"count_site"`
}

func (p *RetSiteCountPrograms) Close() error {
	return _RetSiteCountClose(
		p.CountSite,
	)
}

func _RetSiteCountClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed retsitecount_bpfel.o
var _RetSiteCountBytes []byte
